# Capstone Project

This notebook explores the HMDA dataset for 2024.
We begin by loading and inspecting the data.

In [2]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-2.3.3-cp39-cp39-macosx_11_0_arm64.whl (10.8 MB)
     |████████████████████████████████| 10.8 MB 9.1 MB/s eta 0:00:01
Collecting numpy>=1.22.4
  Downloading numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl (5.3 MB)
     |████████████████████████████████| 5.3 MB 16.2 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/aiww/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1
  Downloading pytz-2026.1.post1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 8.0 MB/s eta 0:00:01
Collecting tzdata>=2022.7
  Downloading tzdata-2026.1-py2.py3-none-any.whl (348 kB)
     |████████████████████████████████| 348 kB 11.8 MB/s eta 0:00:01
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Installing collected packages: tzdata, pytz, numpy, pandas
Successfully installed numpy-2.0.2 pandas-2.3.3 pytz-2026.1.post1 tzdata-2026.1
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pandas as pd

df = pd.read_csv("data/2024_ts.txt", sep="|")
df.head()

,activity_year,calendar_quarter,lei,tax_id,agency_code,respondent_name,respondent_state,respondent_city,respondent_zip_code,lar_count
0,2024,4,01KWVG908KE7RKPTNP46,91-1299114,3,HomeStreet Bank,WA,Seattle,98101,2396
1,2024,4,549300CG5TM73650DH84,95-1981100,5,Christian Community Credit Union,CA,San Dimas,91773,195
2,2024,4,254900IHSG9OOX0DZH92,91-0684272,5,NORTHWEST PLUS CREDIT UNION,WA,EVERETT,98201,35
3,2024,4,984500A9F1AADF548748,20-8780109,7,Commercial Loan Corporation,CA,Newport Beach,92660,41
4,2024,4,549300LL0P3NQ5Q2UF60,95-0944725,5,Long Beach Firemen's Credit Union,CA,Long Beach,90815,2

In [4]:
df.shape

(4926, 10)

In [6]:
df_lar = pd.read_csv(
    "data/2024_lar.txt",
    sep="|",
nrows=100000  # solo muestra

)

df_lar.head()

/var/folders/9h/m28081695mj6xck0r_jgj72c0000gn/T/ipykernel_73156/2736493853.py:1: DtypeWarning: Columns (22,23,24,26,27,28,29,30,31,32,33,38,43,44) have mixed types. Specify dtype option on import or set low_memory=False.
  df_lar = pd.read_csv(

,activity_year,lei,derived_msa_md,state_code,county_code,census_tract,conforming_loan_limit,derived_loan_product_type,derived_dwelling_category,derived_ethnicity,...,denial_reason_2,denial_reason_3,denial_reason_4,tract_population,tract_minority_population_percent,ffiec_msa_md_median_family_income,tract_to_msa_income_percentage,tract_owner_occupied_units,tract_one_to_four_family_homes,tract_median_age_of_housing_units
0,2024,549300K4ZLGS7SRDTL86,99999,PA,42107.0,4.210700e+10,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,...,NaN,NaN,NaN,2238,3.26,81400,113.0,748,1077,53
1,2024,549300K4ZLGS7SRDTL86,29460,FL,12105.0,1.210501e+10,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,...,NaN,NaN,NaN,7175,61.88,76400,74.0,1319,2175,54
2,2024,549300K4ZLGS7SRDTL86,28700,VA,51191.0,5.119101e+10,C,VA:First Lien,Single Family (1-4 Units):Site-Built,Not Hispanic or Latino,...,NaN,NaN,NaN,2620,8.78,70300,106.0,625,938,41
3,2024,549300K4ZLGS7SRDTL86,26420,TX,48157.0,4.815768e+10,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Hispanic or Latino,...,NaN,NaN,NaN,7262,42.43,97400,99.0,2077,2402,27
4,2024,549300K4ZLGS7SRDTL86,33460,MN,27003.0,2.700305e+10,C,FHA:First Lien,Single Family (1-4 Units):Site-Built,Ethnicity Not Available,...,NaN,NaN,NaN,7828,22.94,123700,114.0,2156,2364,13